-- Generated by scripts/generate-clinical-concepts-seed-sql.mjs
-- Input: docs/db/DB_CLINICAL_CONCEPTS_SEED_V2_DRAFT_2026-03-24.json
-- Generated at: 2026-03-24T08:14:14.415Z
--
-- This seed intentionally inserts:
-- - concepts
-- - aliases
-- - relationship rows by concept_key lookup against public.clinical_concepts
--   (so relationships may reference concepts already seeded in previous waves)

begin;
with concept_seed(
  concept_key,
  display,
  display_ko,
  concept_domain,
  specialty_scope,
  source_table,
  source_code,
  evidence_source,
  status,
  properties
) as (
  values
(
  'hip_pain',
  'Hip pain',
  '고관절 통증',
  'condition',
  array['core', 'msk']::text[],
  'terminology_registry',
  'hip_pain',
  'seed:v2-draft-wave1',
  'active',
  '{"seed_version":"v2-draft-wave1"}'::jsonb
),
(
  'radicular_pain',
  'Radicular pain',
  '방사통',
  'condition',
  array['core', 'msk', 'neuro']::text[],
  'terminology_registry',
  'radicular_pain',
  'seed:v2-draft-wave1',
  'active',
  '{"seed_version":"v2-draft-wave1"}'::jsonb
),
(
  'gait_speed',
  'Gait speed',
  '보행 속도',
  'observation',
  array['core', 'neuro', 'wellness']::text[],
  'observation_taxonomy',
  'GAIT_speed',
  'seed:v2-draft-wave1',
  'active',
  '{"seed_version":"v2-draft-wave1"}'::jsonb
),
(
  'balance_deficit',
  'Balance deficit',
  '균형 저하',
  'impairment',
  array['core', 'neuro', 'wellness']::text[],
  null,
  'BBS',
  'seed:v2-draft-wave1',
  'active',
  '{"seed_version":"v2-draft-wave1"}'::jsonb
),
(
  'fall_risk',
  'Fall risk',
  '낙상 위험',
  'risk',
  array['core', 'neuro', 'wellness']::text[],
  null,
  'fall_risk',
  'seed:v2-draft-wave1',
  'active',
  '{"seed_version":"v2-draft-wave1"}'::jsonb
),
(
  'adherence_decline',
  'Adherence decline',
  '순응도 저하',
  'other',
  array['core', 'msk', 'neuro', 'wellness', 'trainer']::text[],
  null,
  'home_program_adherence',
  'seed:v2-draft-wave1',
  'active',
  '{"seed_version":"v2-draft-wave1"}'::jsonb
),
(
  'lumbar_extension_limitation',
  'Lumbar extension limitation',
  '요추 신전 제한',
  'impairment',
  array['core', 'msk']::text[],
  'observation_taxonomy',
  'ROM_lumbar_extension',
  'seed:v2-draft-wave1',
  'active',
  '{"seed_version":"v2-draft-wave1"}'::jsonb
),
(
  'cervical_rotation_limitation',
  'Cervical rotation limitation',
  '경추 회전 제한',
  'impairment',
  array['core', 'msk']::text[],
  'observation_taxonomy',
  'ROM_cervical_rotation',
  'seed:v2-draft-wave1',
  'active',
  '{"seed_version":"v2-draft-wave1"}'::jsonb
),
(
  'shoulder_abduction_limitation',
  'Shoulder abduction limitation',
  '어깨 외전 제한',
  'impairment',
  array['core', 'msk']::text[],
  'observation_taxonomy',
  'ROM_shoulder_abduction',
  'seed:v2-draft-wave1',
  'active',
  '{"seed_version":"v2-draft-wave1"}'::jsonb
),
(
  'hip_abductor_weakness',
  'Hip abductor weakness',
  '고관절 외전근 약화',
  'impairment',
  array['core', 'msk']::text[],
  'observation_taxonomy',
  'MMT_hip_abduction',
  'seed:v2-draft-wave1',
  'active',
  '{"seed_version":"v2-draft-wave1"}'::jsonb
),
(
  'knee_extension_weakness',
  'Knee extension weakness',
  '무릎 신전 약화',
  'impairment',
  array['core', 'msk', 'neuro']::text[],
  'observation_taxonomy',
  'MMT_knee_extension',
  'seed:v2-draft-wave1',
  'active',
  '{"seed_version":"v2-draft-wave1"}'::jsonb
),
(
  'positive_trendelenburg',
  'Positive Trendelenburg test',
  '트렌델렌버그 검사 양성',
  'special_test',
  array['msk', 'neuro']::text[],
  'special_tests',
  'trendelenburg_test',
  'seed:v2-draft-wave1',
  'active',
  '{"seed_version":"v2-draft-wave1"}'::jsonb
),
(
  'positive_prone_instability',
  'Positive prone instability test',
  '엎드린 불안정성 검사 양성',
  'special_test',
  array['msk']::text[],
  'special_tests',
  'prone_instability_test',
  'seed:v2-draft-wave1',
  'active',
  '{"seed_version":"v2-draft-wave1"}'::jsonb
),
(
  'dermatome_deficit',
  'Dermatome deficit',
  '피부분절 감각 저하',
  'impairment',
  array['neuro']::text[],
  null,
  'DERM_C6',
  'seed:v2-draft-wave1',
  'active',
  '{"seed_version":"v2-draft-wave1"}'::jsonb
),
(
  'myotome_deficit',
  'Myotome deficit',
  '근분절 근력 저하',
  'impairment',
  array['neuro']::text[],
  null,
  'MYO_L4',
  'seed:v2-draft-wave1',
  'active',
  '{"seed_version":"v2-draft-wave1"}'::jsonb
),
(
  'reflex_asymmetry',
  'Reflex asymmetry',
  '반사 비대칭',
  'impairment',
  array['neuro']::text[],
  null,
  'REFLEX_L4',
  'seed:v2-draft-wave1',
  'active',
  '{"seed_version":"v2-draft-wave1"}'::jsonb
),
(
  'gait_instability',
  'Gait instability',
  '보행 불안정',
  'movement_pattern',
  array['neuro', 'wellness']::text[],
  'movement_patterns',
  'gait_instability',
  'seed:v2-draft-wave1',
  'active',
  '{"seed_version":"v2-draft-wave1"}'::jsonb
),
(
  'spasticity',
  'Spasticity',
  '경직',
  'impairment',
  array['neuro']::text[],
  null,
  'NEURO_MAS',
  'seed:v2-draft-wave1',
  'active',
  '{"seed_version":"v2-draft-wave1"}'::jsonb
),
(
  'hyperreflexia',
  'Hyperreflexia',
  '반사 항진',
  'impairment',
  array['neuro']::text[],
  null,
  'DTR_patellar',
  'seed:v2-draft-wave1',
  'active',
  '{"seed_version":"v2-draft-wave1"}'::jsonb
),
(
  'pelvic_alignment_asymmetry',
  'Pelvic alignment asymmetry',
  '골반 정렬 비대칭',
  'impairment',
  array['pediatric', 'neuro']::text[],
  null,
  'pelvic_alignment',
  'seed:v2-draft-wave1',
  'active',
  '{"seed_version":"v2-draft-wave1"}'::jsonb
),
(
  'scoliosis',
  'Scoliosis',
  '척추측만',
  'condition',
  array['pediatric', 'neuro']::text[],
  'observation_taxonomy',
  'scoliosis_summary',
  'seed:v2-draft-wave1',
  'active',
  '{"seed_version":"v2-draft-wave1"}'::jsonb
),
(
  'hip_asymmetry',
  'Hip asymmetry',
  '고관절 비대칭',
  'impairment',
  array['pediatric', 'neuro']::text[],
  'observation_taxonomy',
  'hip_status',
  'seed:v2-draft-wave1',
  'active',
  '{"seed_version":"v2-draft-wave1"}'::jsonb
),
(
  'session_tolerance_low',
  'Low session tolerance',
  '세션 내성 저하',
  'other',
  array['pediatric']::text[],
  'observation_taxonomy',
  'session_tolerance',
  'seed:v2-draft-wave1',
  'active',
  '{"seed_version":"v2-draft-wave1"}'::jsonb
),
(
  'caregiver_education_completed',
  'Caregiver education completed',
  '보호자 교육 완료',
  'other',
  array['pediatric']::text[],
  'observation_taxonomy',
  'caregiver_education_checklist',
  'seed:v2-draft-wave1',
  'active',
  '{"seed_version":"v2-draft-wave1"}'::jsonb
),
(
  'aspiration_sign_present',
  'Aspiration sign present',
  '흡인 징후 있음',
  'risk',
  array['pediatric']::text[],
  null,
  'aspiration_risk',
  'seed:v2-draft-wave1',
  'active',
  '{"seed_version":"v2-draft-wave1"}'::jsonb
),
(
  'sleep_quality_low',
  'Low sleep quality',
  '수면 질 저하',
  'observation',
  array['wellness']::text[],
  null,
  'sleep_quality_scale',
  'seed:v2-draft-wave1',
  'active',
  '{"seed_version":"v2-draft-wave1"}'::jsonb
),
(
  'stress_level_high',
  'High stress level',
  '스트레스 수준 높음',
  'risk',
  array['wellness']::text[],
  null,
  'perceived_stress_scale',
  'seed:v2-draft-wave1',
  'active',
  '{"seed_version":"v2-draft-wave1"}'::jsonb
),
(
  'recovery_quality_low',
  'Low recovery quality',
  '회복 질 저하',
  'observation',
  array['wellness', 'trainer']::text[],
  null,
  'sleep_hours',
  'seed:v2-draft-wave1',
  'active',
  '{"seed_version":"v2-draft-wave1"}'::jsonb
),
(
  'readiness_low',
  'Low readiness',
  '준비도 저하',
  'risk',
  array['wellness', 'trainer']::text[],
  null,
  'perceived_readiness',
  'seed:v2-draft-wave1',
  'active',
  '{"seed_version":"v2-draft-wave1"}'::jsonb
),
(
  'jump_power_decline',
  'Jump power decline',
  '점프 파워 저하',
  'movement_pattern',
  array['trainer']::text[],
  null,
  'countermovement_jump',
  'seed:v2-draft-wave1',
  'active',
  '{"seed_version":"v2-draft-wave1"}'::jsonb
),
(
  'agility_decline',
  'Agility decline',
  '민첩성 저하',
  'movement_pattern',
  array['trainer']::text[],
  null,
  't_test_time',
  'seed:v2-draft-wave1',
  'active',
  '{"seed_version":"v2-draft-wave1"}'::jsonb
),
(
  'high_soreness',
  'High soreness',
  '근육통 높음',
  'other',
  array['trainer']::text[],
  null,
  'doms_soreness',
  'seed:v2-draft-wave1',
  'active',
  '{"seed_version":"v2-draft-wave1"}'::jsonb
)
)
insert into public.clinical_concepts (
  concept_key,
  display,
  display_ko,
  concept_domain,
  specialty_scope,
  source_table,
  source_code,
  definition,
  status,
  properties
)
select
  concept_key,
  display,
  display_ko,
  concept_domain,
  specialty_scope,
  source_table,
  source_code,
  evidence_source,
  status,
  properties
from concept_seed
on conflict (concept_key) do update
set
  display = excluded.display,
  display_ko = excluded.display_ko,
  concept_domain = excluded.concept_domain,
  specialty_scope = excluded.specialty_scope,
  source_table = excluded.source_table,
  source_code = excluded.source_code,
  definition = excluded.definition,
  status = excluded.status,
  properties = excluded.properties;
with alias_seed(
  concept_key,
  alias_text,
  normalized_alias,
  language_code,
  alias_type,
  source,
  is_preferred
) as (
  values
(
  'hip_pain',
  'hip pain',
  'hip pain',
  'en',
  'surface_form',
  'seed:v2-draft-wave1',
  false
),
(
  'hip_pain',
  '고관절 통증',
  '고관절 통증',
  'ko',
  'synonym',
  'seed:v2-draft-wave1',
  false
),
(
  'radicular_pain',
  'sciatica',
  'sciatica',
  'en',
  'synonym',
  'seed:v2-draft-wave1',
  false
),
(
  'radicular_pain',
  '방사통',
  '방사통',
  'ko',
  'synonym',
  'seed:v2-draft-wave1',
  false
),
(
  'gait_speed',
  'walking speed',
  'walking speed',
  'en',
  'surface_form',
  'seed:v2-draft-wave1',
  false
),
(
  'gait_speed',
  '보행 속도',
  '보행 속도',
  'ko',
  'synonym',
  'seed:v2-draft-wave1',
  false
),
(
  'balance_deficit',
  'poor balance',
  'poor balance',
  'en',
  'surface_form',
  'seed:v2-draft-wave1',
  false
),
(
  'balance_deficit',
  '균형 저하',
  '균형 저하',
  'ko',
  'synonym',
  'seed:v2-draft-wave1',
  false
),
(
  'fall_risk',
  'risk of falling',
  'risk of falling',
  'en',
  'surface_form',
  'seed:v2-draft-wave1',
  false
),
(
  'fall_risk',
  '낙상 위험',
  '낙상 위험',
  'ko',
  'synonym',
  'seed:v2-draft-wave1',
  false
),
(
  'adherence_decline',
  'poor adherence',
  'poor adherence',
  'en',
  'surface_form',
  'seed:v2-draft-wave1',
  false
),
(
  'adherence_decline',
  '순응도 저하',
  '순응도 저하',
  'ko',
  'synonym',
  'seed:v2-draft-wave1',
  false
),
(
  'lumbar_extension_limitation',
  'lumbar extension loss',
  'lumbar extension loss',
  'en',
  'surface_form',
  'seed:v2-draft-wave1',
  false
),
(
  'lumbar_extension_limitation',
  '요추 신전 제한',
  '요추 신전 제한',
  'ko',
  'synonym',
  'seed:v2-draft-wave1',
  false
),
(
  'cervical_rotation_limitation',
  'limited neck rotation',
  'limited neck rotation',
  'en',
  'surface_form',
  'seed:v2-draft-wave1',
  false
),
(
  'cervical_rotation_limitation',
  '경추 회전 제한',
  '경추 회전 제한',
  'ko',
  'synonym',
  'seed:v2-draft-wave1',
  false
),
(
  'shoulder_abduction_limitation',
  'limited shoulder abduction',
  'limited shoulder abduction',
  'en',
  'surface_form',
  'seed:v2-draft-wave1',
  false
),
(
  'shoulder_abduction_limitation',
  '어깨 외전 제한',
  '어깨 외전 제한',
  'ko',
  'synonym',
  'seed:v2-draft-wave1',
  false
),
(
  'hip_abductor_weakness',
  'glute med weakness',
  'glute med weakness',
  'en',
  'surface_form',
  'seed:v2-draft-wave1',
  false
),
(
  'hip_abductor_weakness',
  '고관절 외전근 약화',
  '고관절 외전근 약화',
  'ko',
  'synonym',
  'seed:v2-draft-wave1',
  false
),
(
  'knee_extension_weakness',
  'quadriceps weakness',
  'quadriceps weakness',
  'en',
  'surface_form',
  'seed:v2-draft-wave1',
  false
),
(
  'knee_extension_weakness',
  '무릎 신전 약화',
  '무릎 신전 약화',
  'ko',
  'synonym',
  'seed:v2-draft-wave1',
  false
),
(
  'positive_trendelenburg',
  'trendelenburg positive',
  'trendelenburg positive',
  'en',
  'surface_form',
  'seed:v2-draft-wave1',
  false
),
(
  'positive_trendelenburg',
  '트렌델렌버그 양성',
  '트렌델렌버그 양성',
  'ko',
  'surface_form',
  'seed:v2-draft-wave1',
  false
),
(
  'positive_prone_instability',
  'prone instability positive',
  'prone instability positive',
  'en',
  'surface_form',
  'seed:v2-draft-wave1',
  false
),
(
  'positive_prone_instability',
  '엎드린 불안정성 검사 양성',
  '엎드린 불안정성 검사 양성',
  'ko',
  'surface_form',
  'seed:v2-draft-wave1',
  false
),
(
  'dermatome_deficit',
  'sensory deficit',
  'sensory deficit',
  'en',
  'surface_form',
  'seed:v2-draft-wave1',
  false
),
(
  'dermatome_deficit',
  '피부분절 감각 저하',
  '피부분절 감각 저하',
  'ko',
  'synonym',
  'seed:v2-draft-wave1',
  false
),
(
  'myotome_deficit',
  'myotomal weakness',
  'myotomal weakness',
  'en',
  'surface_form',
  'seed:v2-draft-wave1',
  false
),
(
  'myotome_deficit',
  '근분절 근력 저하',
  '근분절 근력 저하',
  'ko',
  'synonym',
  'seed:v2-draft-wave1',
  false
),
(
  'reflex_asymmetry',
  'asymmetric reflex',
  'asymmetric reflex',
  'en',
  'surface_form',
  'seed:v2-draft-wave1',
  false
),
(
  'reflex_asymmetry',
  '반사 비대칭',
  '반사 비대칭',
  'ko',
  'synonym',
  'seed:v2-draft-wave1',
  false
),
(
  'gait_instability',
  'unstable gait',
  'unstable gait',
  'en',
  'surface_form',
  'seed:v2-draft-wave1',
  false
),
(
  'gait_instability',
  '보행 불안정',
  '보행 불안정',
  'ko',
  'synonym',
  'seed:v2-draft-wave1',
  false
),
(
  'spasticity',
  'high tone',
  'high tone',
  'en',
  'surface_form',
  'seed:v2-draft-wave1',
  false
),
(
  'spasticity',
  '경직',
  '경직',
  'ko',
  'synonym',
  'seed:v2-draft-wave1',
  false
),
(
  'hyperreflexia',
  'brisk reflexes',
  'brisk reflexes',
  'en',
  'surface_form',
  'seed:v2-draft-wave1',
  false
),
(
  'hyperreflexia',
  '반사 항진',
  '반사 항진',
  'ko',
  'synonym',
  'seed:v2-draft-wave1',
  false
),
(
  'pelvic_alignment_asymmetry',
  'pelvic asymmetry',
  'pelvic asymmetry',
  'en',
  'surface_form',
  'seed:v2-draft-wave1',
  false
),
(
  'pelvic_alignment_asymmetry',
  '골반 정렬 비대칭',
  '골반 정렬 비대칭',
  'ko',
  'synonym',
  'seed:v2-draft-wave1',
  false
),
(
  'scoliosis',
  'spinal curvature',
  'spinal curvature',
  'en',
  'surface_form',
  'seed:v2-draft-wave1',
  false
),
(
  'scoliosis',
  '척추측만',
  '척추측만',
  'ko',
  'synonym',
  'seed:v2-draft-wave1',
  false
),
(
  'hip_asymmetry',
  'uneven hips',
  'uneven hips',
  'en',
  'surface_form',
  'seed:v2-draft-wave1',
  false
),
(
  'hip_asymmetry',
  '고관절 비대칭',
  '고관절 비대칭',
  'ko',
  'synonym',
  'seed:v2-draft-wave1',
  false
),
(
  'session_tolerance_low',
  'low tolerance',
  'low tolerance',
  'en',
  'surface_form',
  'seed:v2-draft-wave1',
  false
),
(
  'session_tolerance_low',
  '세션 내성 저하',
  '세션 내성 저하',
  'ko',
  'surface_form',
  'seed:v2-draft-wave1',
  false
),
(
  'caregiver_education_completed',
  'caregiver education done',
  'caregiver education done',
  'en',
  'surface_form',
  'seed:v2-draft-wave1',
  false
),
(
  'caregiver_education_completed',
  '보호자 교육 완료',
  '보호자 교육 완료',
  'ko',
  'surface_form',
  'seed:v2-draft-wave1',
  false
),
(
  'aspiration_sign_present',
  'aspiration signs',
  'aspiration signs',
  'en',
  'surface_form',
  'seed:v2-draft-wave1',
  false
),
(
  'aspiration_sign_present',
  '흡인 징후',
  '흡인 징후',
  'ko',
  'surface_form',
  'seed:v2-draft-wave1',
  false
),
(
  'sleep_quality_low',
  'poor sleep quality',
  'poor sleep quality',
  'en',
  'surface_form',
  'seed:v2-draft-wave1',
  false
),
(
  'sleep_quality_low',
  '수면 질 저하',
  '수면 질 저하',
  'ko',
  'synonym',
  'seed:v2-draft-wave1',
  false
),
(
  'stress_level_high',
  'high stress',
  'high stress',
  'en',
  'surface_form',
  'seed:v2-draft-wave1',
  false
),
(
  'stress_level_high',
  '스트레스 수준 높음',
  '스트레스 수준 높음',
  'ko',
  'synonym',
  'seed:v2-draft-wave1',
  false
),
(
  'recovery_quality_low',
  'poor recovery',
  'poor recovery',
  'en',
  'surface_form',
  'seed:v2-draft-wave1',
  false
),
(
  'recovery_quality_low',
  '회복 질 저하',
  '회복 질 저하',
  'ko',
  'synonym',
  'seed:v2-draft-wave1',
  false
),
(
  'readiness_low',
  'low readiness',
  'low readiness',
  'en',
  'surface_form',
  'seed:v2-draft-wave1',
  false
),
(
  'readiness_low',
  '준비도 저하',
  '준비도 저하',
  'ko',
  'synonym',
  'seed:v2-draft-wave1',
  false
),
(
  'jump_power_decline',
  'jump power drop',
  'jump power drop',
  'en',
  'surface_form',
  'seed:v2-draft-wave1',
  false
),
(
  'jump_power_decline',
  '점프 파워 저하',
  '점프 파워 저하',
  'ko',
  'synonym',
  'seed:v2-draft-wave1',
  false
),
(
  'agility_decline',
  'slower agility',
  'slower agility',
  'en',
  'surface_form',
  'seed:v2-draft-wave1',
  false
),
(
  'agility_decline',
  '민첩성 저하',
  '민첩성 저하',
  'ko',
  'synonym',
  'seed:v2-draft-wave1',
  false
),
(
  'high_soreness',
  'severe soreness',
  'severe soreness',
  'en',
  'surface_form',
  'seed:v2-draft-wave1',
  false
),
(
  'high_soreness',
  '근육통 높음',
  '근육통 높음',
  'ko',
  'synonym',
  'seed:v2-draft-wave1',
  false
)
)
insert into public.concept_aliases (
  concept_id,
  alias_text,
  normalized_alias,
  language_code,
  alias_type,
  source,
  is_preferred
)
select
  cc.id,
  a.alias_text,
  a.normalized_alias,
  a.language_code,
  a.alias_type,
  a.source,
  a.is_preferred
from alias_seed a
join public.clinical_concepts cc
  on cc.concept_key = a.concept_key
on conflict (concept_id, normalized_alias, language_code, alias_type) do update
set
  alias_text = excluded.alias_text,
  source = excluded.source,
  is_preferred = excluded.is_preferred;
with relationship_seed(
  source_concept_key,
  relationship_type,
  target_concept_key,
  weight,
  specialty_scope,
  evidence_source
) as (
  values
(
  'positive_slr',
  'indicates',
  'radicular_pain',
  1,
  array['msk', 'neuro']::text[],
  'seed:v2-draft-wave1'
),
(
  'slump_test_positive',
  'indicates',
  'radicular_pain',
  1,
  array['msk', 'neuro']::text[],
  'seed:v2-draft-wave1'
),
(
  'positive_trendelenburg',
  'indicates',
  'hip_abductor_weakness',
  1,
  array['msk', 'neuro']::text[],
  'seed:v2-draft-wave1'
),
(
  'positive_prone_instability',
  'indicates',
  'trunk_instability',
  1,
  array['msk']::text[],
  'seed:v2-draft-wave1'
),
(
  'balance_deficit',
  'increases_risk_of',
  'fall_risk',
  1,
  array['core', 'neuro', 'wellness']::text[],
  'seed:v2-draft-wave1'
),
(
  'gait_instability',
  'increases_risk_of',
  'fall_risk',
  1,
  array['neuro', 'wellness']::text[],
  'seed:v2-draft-wave1'
),
(
  'aspiration_sign_present',
  'increases_risk_of',
  'aspiration_risk',
  1,
  array['pediatric']::text[],
  'seed:v2-draft-wave1'
),
(
  'feeding_route',
  'related_to',
  'aspiration_risk',
  1,
  array['pediatric']::text[],
  'seed:v2-draft-wave1'
),
(
  'head_control_deficit',
  'related_to',
  'trunk_control_deficit',
  1,
  array['pediatric', 'neuro']::text[],
  'seed:v2-draft-wave1'
),
(
  'hip_asymmetry',
  'related_to',
  'scoliosis',
  1,
  array['pediatric', 'neuro']::text[],
  'seed:v2-draft-wave1'
)
)
insert into public.concept_relationships (
  source_concept_id,
  relationship_type,
  target_concept_id,
  weight,
  specialty_scope,
  evidence_source
)
select
  src.id,
  r.relationship_type,
  tgt.id,
  r.weight,
  r.specialty_scope,
  r.evidence_source
from relationship_seed r
join public.clinical_concepts src
  on src.concept_key = r.source_concept_key
join public.clinical_concepts tgt
  on tgt.concept_key = r.target_concept_key
on conflict (source_concept_id, relationship_type, target_concept_id) do update
set
  weight = excluded.weight,
  specialty_scope = excluded.specialty_scope,
  evidence_source = excluded.evidence_source;
commit;
-- Relationships that reference concept keys outside the current input file:
-- positive_slr indicates radicular_pain
-- slump_test_positive indicates radicular_pain
-- positive_prone_instability indicates trunk_instability
-- aspiration_sign_present increases_risk_of aspiration_risk
-- feeding_route related_to aspiration_risk
-- head_control_deficit related_to trunk_control_deficit;
