-- PT Observation Taxonomy Wave 1A
-- Safe exact-new insert subset only.
--
-- Intentionally excluded from this wave because live precheck showed existing rows
-- or naming alignment ambiguity:
-- - MMT_hip_abduction
-- - MMT_hip_extension
-- - MMT_trunk_flexion
-- - gait_speed / GAIT_speed
--
-- Follow-up alignment wave should handle existing-code normalization separately.

insert into public.observation_taxonomy (
  code,
  code_display,
  category,
  code_system,
  default_value_type,
  default_unit,
  unit_system,
  body_site_applicable,
  laterality_applicable,
  is_required_typed,
  is_active,
  notes
)
values
  (
    'MMT_shoulder_abduction',
    'Shoulder abduction MMT',
    array['strength','function'],
    'http://physiokorea.com/fhir/observation',
    'json',
    null,
    null,
    true,
    true,
    true,
    true,
    'PT exam Wave 1A: MMT stored as json to preserve ordinal grade and nuance.'
  ),
  (
    'MMT_elbow_flexion',
    'Elbow flexion MMT',
    array['strength','function'],
    'http://physiokorea.com/fhir/observation',
    'json',
    null,
    null,
    true,
    true,
    true,
    true,
    'PT exam Wave 1A: MMT stored as json to preserve ordinal grade and nuance.'
  ),
  (
    'MMT_wrist_extension',
    'Wrist extension MMT',
    array['strength','function','neuro'],
    'http://physiokorea.com/fhir/observation',
    'json',
    null,
    null,
    true,
    true,
    true,
    true,
    'PT exam Wave 1A: useful for myotome-style neuro screening.'
  ),
  (
    'MMT_knee_extension',
    'Knee extension MMT',
    array['strength','function'],
    'http://physiokorea.com/fhir/observation',
    'json',
    null,
    null,
    true,
    true,
    true,
    true,
    'PT exam Wave 1A.'
  ),
  (
    'MMT_ankle_dorsiflexion',
    'Ankle dorsiflexion MMT',
    array['strength','function','neuro'],
    'http://physiokorea.com/fhir/observation',
    'json',
    null,
    null,
    true,
    true,
    true,
    true,
    'PT exam Wave 1A.'
  ),
  (
    'MMT_great_toe_extension',
    'Great toe extension MMT',
    array['strength','neuro'],
    'http://physiokorea.com/fhir/observation',
    'json',
    null,
    null,
    true,
    true,
    true,
    true,
    'PT exam Wave 1A: useful for L5-oriented motor screening.'
  ),
  (
    'gait_pattern',
    'Gait pattern',
    array['gait','function'],
    'http://physiokorea.com/fhir/observation',
    'string',
    null,
    null,
    false,
    false,
    true,
    true,
    'PT exam Wave 1A: qualitative gait label.'
  ),
  (
    'gait_assistance_level',
    'Gait assistance level',
    array['gait','function'],
    'http://physiokorea.com/fhir/observation',
    'string',
    null,
    null,
    false,
    false,
    true,
    true,
    'PT exam Wave 1A.'
  ),
  (
    'gait_endurance_distance',
    'Gait endurance distance',
    array['gait','function','endurance'],
    'http://physiokorea.com/fhir/observation',
    'quantity',
    'm',
    'http://unitsofmeasure.org',
    false,
    false,
    true,
    true,
    'PT exam Wave 1A.'
  ),
  (
    'TUG_seconds',
    'Timed Up and Go',
    array['balance','function','mobility'],
    'http://physiokorea.com/fhir/observation',
    'quantity',
    's',
    'http://unitsofmeasure.org',
    false,
    false,
    true,
    true,
    'PT exam Wave 1A.'
  ),
  (
    'BBS_total',
    'Berg Balance Scale total',
    array['balance','function'],
    'http://physiokorea.com/fhir/observation',
    'integer',
    'score',
    null,
    false,
    false,
    true,
    true,
    'PT exam Wave 1A.'
  ),
  (
    'single_leg_stance_seconds',
    'Single-leg stance time',
    array['balance','function'],
    'http://physiokorea.com/fhir/observation',
    'quantity',
    's',
    'http://unitsofmeasure.org',
    true,
    true,
    true,
    true,
    'PT exam Wave 1A.'
  ),
  (
    'five_times_sit_to_stand_seconds',
    'Five times sit-to-stand',
    array['balance','function','mobility'],
    'http://physiokorea.com/fhir/observation',
    'quantity',
    's',
    'http://unitsofmeasure.org',
    false,
    false,
    true,
    true,
    'PT exam Wave 1A.'
  ),
  (
    'six_minute_walk_distance',
    'Six-minute walk distance',
    array['endurance','function'],
    'http://physiokorea.com/fhir/observation',
    'quantity',
    'm',
    'http://unitsofmeasure.org',
    false,
    false,
    true,
    true,
    'PT exam Wave 1A.'
  ),
  (
    'ten_meter_walk_speed',
    'Ten-meter walk speed',
    array['gait','function'],
    'http://physiokorea.com/fhir/observation',
    'quantity',
    'm/s',
    'http://unitsofmeasure.org',
    false,
    false,
    true,
    true,
    'PT exam Wave 1A.'
  ),
  (
    'special_test_slr',
    'Straight Leg Raise',
    array['special_test','neuro','msk'],
    'http://physiokorea.com/fhir/observation',
    'json',
    null,
    null,
    true,
    true,
    true,
    true,
    'PT exam Wave 1A: use json for angle and symptom reproduction.'
  ),
  (
    'special_test_slump',
    'Slump test',
    array['special_test','neuro','msk'],
    'http://physiokorea.com/fhir/observation',
    'json',
    null,
    null,
    true,
    true,
    true,
    true,
    'PT exam Wave 1A: use json for symptom reproduction detail.'
  ),
  (
    'special_test_lachman',
    'Lachman test',
    array['special_test','msk'],
    'http://physiokorea.com/fhir/observation',
    'boolean',
    null,
    null,
    true,
    true,
    true,
    true,
    'PT exam Wave 1A.'
  ),
  (
    'special_test_thompson',
    'Thompson test',
    array['special_test','msk'],
    'http://physiokorea.com/fhir/observation',
    'boolean',
    null,
    null,
    true,
    true,
    true,
    true,
    'PT exam Wave 1A.'
  ),
  (
    'special_test_spurling',
    'Spurling test',
    array['special_test','neuro','msk'],
    'http://physiokorea.com/fhir/observation',
    'boolean',
    null,
    null,
    true,
    true,
    true,
    true,
    'PT exam Wave 1A.'
  ),
  (
    'special_test_faber',
    'FABER test',
    array['special_test','msk'],
    'http://physiokorea.com/fhir/observation',
    'boolean',
    null,
    null,
    true,
    true,
    true,
    true,
    'PT exam Wave 1A.'
  ),
  (
    'special_test_fadir',
    'FADIR test',
    array['special_test','msk'],
    'http://physiokorea.com/fhir/observation',
    'boolean',
    null,
    null,
    true,
    true,
    true,
    true,
    'PT exam Wave 1A.'
  ),
  (
    'special_test_neer',
    'Neer impingement test',
    array['special_test','msk'],
    'http://physiokorea.com/fhir/observation',
    'boolean',
    null,
    null,
    true,
    true,
    true,
    true,
    'PT exam Wave 1A.'
  ),
  (
    'special_test_hawkins_kennedy',
    'Hawkins-Kennedy test',
    array['special_test','msk'],
    'http://physiokorea.com/fhir/observation',
    'boolean',
    null,
    null,
    true,
    true,
    true,
    true,
    'PT exam Wave 1A.'
  )
on conflict (code, code_system) do nothing;
