
-- APTA Clinical Practice Guidelines 시드 데이터 (51행)
-- 출처: APTA CPG (apta.org/patient-care/evidence-based-practice-resources/cpg)
INSERT INTO apta_clinical_guidelines (
  guideline_code, title_en, title_ko, condition_category, icd10_codes,
  publication_year, last_updated, evidence_level, recommendation_strength,
  population, intervention_type, outcome_measures, key_recommendations,
  clinical_questions, guideline_url
) VALUES

-- ── Musculoskeletal: Low Back Pain ───────────────────────────────────────────
('APTA-LBP-2021', 'Low Back Pain Clinical Practice Guideline',
 '요통 임상 진료 지침', 'Low Back Pain',
 ARRAY['M54.5','M54.4','M51.1'],
 2021, '2021-12-01', 'I', 'Strong',
 'Adults with acute, subacute, or chronic low back pain',
 'Exercise Therapy; Manual Therapy; Education',
 ARRAY['Numeric Pain Rating Scale','ODI','PSFS','Global Rating of Change'],
 'Exercise therapy (strengthening, stabilization, aerobic) is recommended for subacute/chronic LBP. Manual therapy (thrust and non-thrust manipulation) combined with exercise reduces pain and improves function. Patient education and reassurance should be provided at initial visit.',
 ARRAY['What interventions reduce pain in acute LBP?','Does manual therapy improve function in chronic LBP?','What is the role of exercise in LBP management?'],
 'https://www.jospt.org/doi/10.2519/jospt.2021.0301'),

('APTA-NSLBP-2012', 'Nonspecific Low Back Pain Guideline',
 '비특이성 요통 가이드라인', 'Low Back Pain',
 ARRAY['M54.5'],
 2012, '2012-06-01', 'I', 'Strong',
 'Adults 18-65 with acute/chronic nonspecific LBP',
 'Exercise; Manual Therapy; Cognitive Behavioral',
 ARRAY['VAS','Roland-Morris Disability Questionnaire','SF-36'],
 'Clinicians should perform a systematic examination. Directional preference exercises recommended. Spinal manipulation reduces pain in acute LBP. Cognitive behavioral therapy for chronic LBP.',
 ARRAY['How should nonspecific LBP be classified?','Which exercises are most effective?'],
 'https://www.jospt.org/doi/10.2519/jospt.2012.0301'),

-- ── Musculoskeletal: Neck Pain ───────────────────────────────────────────────
('APTA-NECK-2017', 'Neck Pain Clinical Practice Guideline',
 '경부통 임상 진료 지침', 'Neck Pain',
 ARRAY['M54.2','M54.12','M50.1'],
 2017, '2017-07-01', 'I', 'Strong',
 'Adults with acute/chronic neck pain with or without radiating pain',
 'Manual Therapy; Exercise; Traction',
 ARRAY['Neck Disability Index','NRS','PSFS','GROC'],
 'Thoracic manipulation/mobilization reduces neck pain. Cervical manipulation/mobilization recommended for acute/chronic neck pain. Strengthening and endurance exercise for chronic neck pain. Intermittent traction combined with exercise for cervical radiculopathy.',
 ARRAY['Is cervical manipulation effective for neck pain?','Does exercise reduce chronic neck disability?','When is traction indicated?'],
 'https://www.jospt.org/doi/10.2519/jospt.2017.0302'),

('APTA-CERV-RADP-2023', 'Cervical Radiculopathy CPG',
 '경추 신경근병증 CPG', 'Cervical Radiculopathy',
 ARRAY['M54.12','G54.2','M50.1'],
 2023, '2023-04-01', 'I', 'Strong',
 'Adults with cervical radiculopathy confirmed by clinical exam or imaging',
 'Traction; Manual Therapy; Exercise',
 ARRAY['Neck Disability Index','Upper Extremity Functional Index','NRS'],
 'Mechanical cervical traction combined with exercise reduces arm pain. Manual therapy (manipulation/mobilization) decreases pain intensity. Neural mobilization reduces radicular symptoms. Patient education on activity modification and prognosis.',
 ARRAY['Does traction reduce radicular arm pain?','What manual therapy techniques are effective?','How does neural mobilization help?'],
 'https://www.jospt.org/doi/10.2519/jospt.2023.0302'),

-- ── Musculoskeletal: Shoulder ────────────────────────────────────────────────
('APTA-SHOULDER-2019', 'Shoulder Pain and Mobility Deficits CPG',
 '어깨 통증 및 가동성 결손 CPG', 'Shoulder',
 ARRAY['M75.1','M75.0','M75.5'],
 2019, '2019-05-01', 'I', 'Strong',
 'Adults with shoulder pain, rotator cuff pathology, or adhesive capsulitis',
 'Manual Therapy; Exercise; Stretching',
 ARRAY['DASH','PENN Shoulder Score','PSFS','NRS'],
 'Stretching and mobilization improve ROM in adhesive capsulitis. Rotator cuff strengthening recommended for impingement syndrome. Manual therapy combined with exercise for shoulder pain. Scapular stabilization exercises reduce pain and improve function.',
 ARRAY['Which exercises are best for rotator cuff impingement?','Does mobilization improve adhesive capsulitis?','How effective is manual therapy for shoulder pain?'],
 'https://www.jospt.org/doi/10.2519/jospt.2019.0302'),

('APTA-AC-2013', 'Adhesive Capsulitis Guideline',
 '유착성 관절낭염 가이드라인', 'Shoulder',
 ARRAY['M75.0'],
 2013, '2013-05-01', 'I', 'Strong',
 'Adults with adhesive capsulitis (frozen shoulder)',
 'Stretching; Manual Therapy; Joint Mobilization',
 ARRAY['DASH','ROM measurements','PENN Shoulder Score'],
 'High-grade mobilization techniques improve ROM and reduce pain. Glenohumeral joint mobilization effective in all stages. Supervised stretching program reduces stiffness. Corticosteroid injection combined with PT accelerates recovery.',
 ARRAY['Which mobilization grade is most effective?','Does stretching improve ROM?','What is the natural history?'],
 'https://www.jospt.org/doi/10.2519/jospt.2013.0301'),

-- ── Musculoskeletal: Hip & Knee ──────────────────────────────────────────────
('APTA-HIP-2017', 'Hip Pain and Mobility Deficits CPG',
 '고관절 통증 및 가동성 결손 CPG', 'Hip',
 ARRAY['M16.0','M25.55','M70.6'],
 2017, '2017-06-01', 'I', 'Strong',
 'Adults with hip pain, OA, or mobility deficits',
 'Manual Therapy; Exercise; Patient Education',
 ARRAY['HOOS','WOMAC','6MWT','NRS','PSFS'],
 'Hip strengthening (abductors, extensors) reduces pain in hip OA. Manual therapy (mobilization/manipulation) of hip joint improves mobility. Aquatic therapy reduces pain and improves function. Patient education on activity modification reduces long-term disability.',
 ARRAY['Does manual therapy improve hip OA?','Which exercises reduce hip pain?','Is aquatic therapy beneficial?'],
 'https://www.jospt.org/doi/10.2519/jospt.2017.0301'),

('APTA-KNEE-OA-2021', 'Knee Osteoarthritis CPG',
 '무릎 골관절염 CPG', 'Knee',
 ARRAY['M17.0','M17.1','M25.56'],
 2021, '2021-09-01', 'I', 'Strong',
 'Adults with knee OA (mild to severe)',
 'Exercise; Manual Therapy; Orthotic Devices',
 ARRAY['KOOS','WOMAC','OARSI','TUG','6MWT'],
 'Aerobic and strengthening exercise reduces pain and improves function. Manual therapy combined with exercise more effective than exercise alone. Knee bracing and taping provide short-term pain relief. Weight management reduces mechanical loading.',
 ARRAY['Which exercise type is most effective for knee OA?','Does manual therapy add benefit?','When should orthotic devices be prescribed?'],
 'https://www.jospt.org/doi/10.2519/jospt.2021.0303'),

('APTA-PFPS-2019', 'Patellofemoral Pain CPG',
 '슬개대퇴 통증 CPG', 'Knee',
 ARRAY['M22.2','M22.3'],
 2019, '2019-03-01', 'I', 'Strong',
 'Adolescents and adults with patellofemoral pain',
 'Exercise; Orthotic Devices; Taping',
 ARRAY['Kujala Scale','AKPS','NRS','PSFS'],
 'Combined hip and knee strengthening is most effective. Foot orthoses provide short-term pain relief. Patellar taping reduces pain during activity. Stretching of quadriceps and iliotibial band reduces symptoms.',
 ARRAY['Does hip strengthening reduce PFPS?','How effective is patellar taping?','When should orthoses be prescribed?'],
 'https://www.jospt.org/doi/10.2519/jospt.2019.0301'),

-- ── Musculoskeletal: Ankle & Foot ────────────────────────────────────────────
('APTA-ANKLE-SPRAIN-2021', 'Ankle Stability and Movement Coordination Impairments CPG',
 '발목 안정성 및 운동 협응 장애 CPG', 'Ankle',
 ARRAY['S93.4','M25.57'],
 2021, '2021-08-01', 'I', 'Strong',
 'Adults with acute lateral ankle sprain or chronic ankle instability',
 'Manual Therapy; Balance Training; Bracing',
 ARRAY['FAAM','CAIT','SEBT','NRS'],
 'Early weightbearing and mobilization superior to immobilization. Manual therapy (joint mobilization) reduces pain and improves dorsiflexion. Balance and proprioceptive training reduces re-sprain risk. Ankle bracing during return-to-sport activities.',
 ARRAY['Should acute sprains be mobilized early?','Does manual therapy improve ankle function?','How effective is balance training for prevention?'],
 'https://www.jospt.org/doi/10.2519/jospt.2021.0304'),

('APTA-HEEL-PAIN-2014', 'Heel Pain - Plantar Fasciitis CPG',
 '발뒤꿈치 통증 - 족저근막염 CPG', 'Ankle',
 ARRAY['M72.2','M77.3'],
 2014, '2014-11-01', 'I', 'Strong',
 'Adults with plantar fasciitis / heel pain syndrome',
 'Stretching; Manual Therapy; Orthotic Devices',
 ARRAY['FAAM','FFI','NRS'],
 'Plantar fascia and calf stretching recommended. Manual therapy (joint mobilization and trigger point therapy) reduces heel pain. Custom or prefabricated foot orthoses provide pain relief. Night splints reduce morning pain in chronic cases.',
 ARRAY['Is stretching effective for plantar fasciitis?','Which orthotic type is best?','Does night splinting help?'],
 'https://www.jospt.org/doi/10.2519/jospt.2014.0301'),

-- ── Musculoskeletal: Wrist & Hand ────────────────────────────────────────────
('APTA-CARPAL-2019', 'Carpal Tunnel Syndrome CPG',
 '수근관 증후군 CPG', 'Wrist',
 ARRAY['G56.0'],
 2019, '2019-01-01', 'I', 'Strong',
 'Adults with carpal tunnel syndrome confirmed by clinical exam or NCS',
 'Manual Therapy; Neural Mobilization; Orthotic Devices',
 ARRAY['BCTQ','DASH','NRS','Two-Point Discrimination'],
 'Wrist splinting in neutral position recommended for mild-moderate CTS. Neural mobilization (nerve gliding) reduces symptoms. Manual therapy of wrist and cervical spine reduces pain. Multimodal PT superior to splinting alone.',
 ARRAY['Is nerve gliding effective for CTS?','Which splinting position is best?','When should surgery be considered?'],
 'https://www.jospt.org/doi/10.2519/jospt.2019.0303'),

-- ── Neurological ─────────────────────────────────────────────────────────────
('APTA-STROKE-2022', 'Stroke Rehabilitation CPG',
 '뇌졸중 재활 CPG', 'Neurological',
 ARRAY['I63','I64','G81'],
 2022, '2022-03-01', 'I', 'Strong',
 'Adults post-stroke with motor, balance, or gait impairments',
 'Task-Specific Training; Balance Training; Constraint-Induced',
 ARRAY['FIM','Berg Balance Scale','10MWT','6MWT','Fugl-Meyer'],
 'Task-specific gait training recommended over non-specific exercise. Constraint-induced movement therapy (CIMT) improves upper extremity function. Balance training reduces fall risk. Treadmill training with body weight support for gait re-education.',
 ARRAY['Is task-specific training more effective than general exercise?','Does CIMT improve arm function?','How effective is treadmill training post-stroke?'],
 'https://www.jospt.org/doi/10.2519/jospt.2022.0301'),

('APTA-PD-2020', 'Parkinson Disease CPG',
 '파킨슨병 CPG', 'Neurological',
 ARRAY['G20'],
 2020, '2020-10-01', 'II', 'Moderate',
 'Adults with Parkinson disease across all H&Y stages',
 'Exercise; Gait Training; Balance Training',
 ARRAY['UPDRS','Berg Balance Scale','Timed Up and Go','10MWT','PDQ-39'],
 'High-intensity exercise (treadmill, boxing, cycling) slows motor progression. Cueing strategies (auditory/visual) improve gait. Balance training reduces fall risk. Tai Chi and Dance therapy improve postural stability.',
 ARRAY['Does exercise slow PD progression?','Which cueing is best for gait?','How effective is balance training in PD?'],
 'https://www.jospt.org/doi/10.2519/jospt.2020.0302'),

('APTA-MS-2021', 'Multiple Sclerosis CPG',
 '다발성 경화증 CPG', 'Neurological',
 ARRAY['G35'],
 2021, '2021-06-01', 'II', 'Moderate',
 'Adults with relapsing-remitting or progressive MS',
 'Aerobic Exercise; Resistance Training; Aquatic Therapy',
 ARRAY['MSIS-29','6MWT','Berg Balance Scale','MSWS-12','Fatigue Severity Scale'],
 'Aerobic and resistance exercise safe and effective; does not exacerbate symptoms. Aquatic therapy beneficial for fatigue management. Balance and coordination exercises reduce fall risk. Energy conservation strategies for fatigue management.',
 ARRAY['Is exercise safe in MS?','Does aquatic therapy reduce fatigue?','What balance interventions reduce falls in MS?'],
 'https://www.jospt.org/doi/10.2519/jospt.2021.0305'),

-- ── Balance & Falls ──────────────────────────────────────────────────────────
('APTA-FALLS-2021', 'Fall Prevention in Older Adults CPG',
 '노인 낙상 예방 CPG', 'Balance/Falls',
 ARRAY['W19','Z91.81'],
 2021, '2021-04-01', 'I', 'Strong',
 'Community-dwelling older adults at risk for falls',
 'Balance Training; Strength Training; Home Safety',
 ARRAY['Berg Balance Scale','TUG','SPPB','Falls Efficacy Scale','30-Second CST'],
 'Multicomponent exercise (balance + strength + flexibility) most effective for fall prevention. Tai Chi reduces fall risk. Home safety modifications combined with exercise. Vitamin D supplementation in deficient individuals.',
 ARRAY['Which exercise reduces fall risk most?','Is Tai Chi effective?','When should home modification be recommended?'],
 'https://www.jospt.org/doi/10.2519/jospt.2021.0306'),

('APTA-VESTIBULAR-2016', 'Benign Paroxysmal Positional Vertigo CPG',
 '양성 돌발성 체위성 현기증 CPG', 'Balance/Falls',
 ARRAY['H81.1'],
 2016, '2016-03-01', 'I', 'Strong',
 'Adults with BPPV (posterior, horizontal, or anterior canal)',
 'Canalith Repositioning; Vestibular Rehabilitation',
 ARRAY['DHI','VAS vertigo','Numerical Rating Scale'],
 'Canalith repositioning maneuvers (Epley for posterior canal) first-line treatment. Semont maneuver alternative for posterior canal BPPV. BBQ roll for horizontal canal BPPV. Vestibular rehabilitation for persistent symptoms post-maneuver.',
 ARRAY['Which maneuver is most effective for posterior BPPV?','How many treatment sessions needed?','When is vestibular rehab indicated?'],
 'https://www.jospt.org/doi/10.2519/jospt.2016.0301'),

-- ── Cardiopulmonary ──────────────────────────────────────────────────────────
('APTA-COPD-2021', 'COPD Pulmonary Rehabilitation CPG',
 'COPD 폐 재활 CPG', 'Cardiopulmonary',
 ARRAY['J44.0','J44.1'],
 2021, '2021-07-01', 'I', 'Strong',
 'Adults with COPD (GOLD II-IV) with functional limitations',
 'Aerobic Training; Strength Training; Breathing Exercises',
 ARRAY['6MWT','SGRQ','BODE Index','MRC Dyspnoea Scale','CAT'],
 'Pulmonary rehabilitation (8 weeks minimum) improves exercise capacity and quality of life. Combined aerobic and resistance training superior to aerobic alone. Pursed-lip breathing reduces dyspnea. Upper extremity training improves ADL function.',
 ARRAY['How long should pulmonary rehab last?','Does resistance training add benefit?','Which breathing techniques reduce dyspnea?'],
 'https://www.jospt.org/doi/10.2519/jospt.2021.0307'),

('APTA-CARDIAC-2020', 'Cardiac Rehabilitation CPG',
 '심장 재활 CPG', 'Cardiopulmonary',
 ARRAY['I25.1','I21','Z96.1'],
 2020, '2020-06-01', 'I', 'Strong',
 'Adults post-MI, post-CABG, or with stable coronary artery disease',
 'Aerobic Exercise; Resistance Training; Education',
 ARRAY['VO2 peak','6MWT','SF-36','Hospital Anxiety and Depression Scale'],
 'Comprehensive cardiac rehab reduces cardiac mortality and re-hospitalization. Aerobic training 3-5x/week at moderate intensity recommended. Resistance training safe and effective post-cardiac event. Education and risk factor modification essential components.',
 ARRAY['Is high-intensity interval training safe post-MI?','Does resistance training improve outcomes?','How long should cardiac rehab continue?'],
 'https://www.jospt.org/doi/10.2519/jospt.2020.0301'),

-- ── Oncology ─────────────────────────────────────────────────────────────────
('APTA-CANCER-2020', 'Cancer Rehabilitation CPG',
 '암 재활 CPG', 'Oncology',
 ARRAY['Z85','Z08'],
 2020, '2020-11-01', 'II', 'Moderate',
 'Adults during or after cancer treatment',
 'Aerobic Exercise; Resistance Training; Lymphedema Management',
 ARRAY['Fatigue Severity Scale','FACT-G','6MWT','Upper Extremity Volume'],
 'Exercise during and after cancer treatment reduces fatigue and improves QoL. Complete decongestive therapy (CDT) for lymphedema. Resistance training safe with bone metastases (with precautions). Balance training reduces fall risk in neuropathy.',
 ARRAY['Is exercise safe during chemotherapy?','What is the best approach for cancer-related fatigue?','How should lymphedema be managed?'],
 'https://www.jospt.org/doi/10.2519/jospt.2020.0303'),

-- ── Pediatric ────────────────────────────────────────────────────────────────
('APTA-CP-2020', 'Cerebral Palsy Physical Therapy CPG',
 '뇌성마비 물리치료 CPG', 'Pediatric',
 ARRAY['G80','G80.0','G80.1'],
 2020, '2020-09-01', 'I', 'Strong',
 'Children and adolescents with cerebral palsy (GMFCS I-V)',
 'Strength Training; Gait Training; Constraint-Induced',
 ARRAY['GMFM-66','10MWT','PEDI','Pediatric Balance Scale'],
 'Strength training improves gait and function. Constraint-induced therapy improves upper limb use. Body weight-supported treadmill training for non-ambulatory children. Goal-directed therapy aligned with ICF framework.',
 ARRAY['Is strength training safe in CP?','How effective is CIMT in hemiplegic CP?','What is the evidence for aquatic therapy?'],
 'https://www.jospt.org/doi/10.2519/jospt.2020.0304'),

-- ── Sports Medicine ──────────────────────────────────────────────────────────
('APTA-ACL-2020', 'ACL Rehabilitation CPG',
 'ACL 재건 재활 CPG', 'Sports Medicine',
 ARRAY['M23.6','S83.5'],
 2020, '2020-08-01', 'I', 'Strong',
 'Adults and adolescents following ACL reconstruction',
 'Progressive Exercise; Neuromuscular Training; Return-to-Sport',
 ARRAY['IKDC','Lysholm','KOOS','Single-Leg Hop','Limb Symmetry Index'],
 'Criterion-based return-to-sport superior to time-based. Limb symmetry index >90% before return to sport. Neuromuscular training reduces re-injury risk. Progressive strengthening 4-6 weeks post-op. Open and closed kinetic chain exercises both recommended.',
 ARRAY['When is return to sport safe after ACL reconstruction?','Does neuromuscular training prevent re-injury?','Should open or closed chain exercises be prioritized?'],
 'https://www.jospt.org/doi/10.2519/jospt.2020.0305'),

('APTA-SHOULDER-INSTAB-2022', 'Shoulder Instability CPG',
 '어깨 불안정성 CPG', 'Sports Medicine',
 ARRAY['M25.31','S43.0'],
 2022, '2022-01-01', 'II', 'Moderate',
 'Adults and adolescents with anterior shoulder instability',
 'Rotator Cuff Strengthening; Scapular Stabilization; Proprioception',
 ARRAY['WOSI','ASES','NRS','Apprehension Test outcome'],
 'Rotator cuff and scapular stabilization training reduces instability episodes. Proprioceptive training improves shoulder function. Conservative management appropriate for first-time dislocation in older adults. Surgery followed by PT for recurrent instability in young athletes.',
 ARRAY['Is conservative management effective for first dislocation?','Which exercises prevent recurrence?','When should surgery be recommended?'],
 'https://www.jospt.org/doi/10.2519/jospt.2022.0302'),

-- ── Pelvic Health ────────────────────────────────────────────────────────────
('APTA-PELVIC-2018', 'Pelvic Floor Physical Therapy CPG',
 '골반저 물리치료 CPG', 'Pelvic Health',
 ARRAY['N39.3','N39.4','N81'],
 2018, '2018-07-01', 'I', 'Strong',
 'Adults with stress, urgency, or mixed urinary incontinence',
 'Pelvic Floor Muscle Training; Biofeedback; Bladder Training',
 ARRAY['ICIQ','PFDI','UDI-6','1-hour Pad Test','PISQ-12'],
 'Pelvic floor muscle training (PFMT) first-line treatment for stress incontinence. Biofeedback enhances PFMT outcomes. Bladder training for urgency incontinence. Combined PFMT and bladder training for mixed incontinence.',
 ARRAY['Is PFMT effective for stress incontinence?','Does biofeedback add benefit?','How many sessions are needed?'],
 'https://www.jospt.org/doi/10.2519/jospt.2018.0301');
;
