-- Secondary ROM L3 wave 11.
-- Generated by scripts/generate-ontology-wave-migration.mjs.
--
-- Purpose:
-- - Promote an existing observation -> capability -> exercise requirement family to MVP L3.
-- - Store cutoff/severity/laterality/regression guidance as rule metadata.
--
-- Clinical safety note:
-- These are MVP exercise-matching defaults, not diagnosis or final clinical policy.
-- Review per population, condition, irritability, symptom response, and clinician judgment
-- before using as strong automated prescribing rules.

do $$
declare
  missing_capabilities text[];
  missing_observations text[];
begin
  select array_agg(seed.capability_code order by seed.capability_code)
  into missing_capabilities
  from (
    values
      ('shoulder_abduction_rom'),
      ('shoulder_internal_rotation_rom'),
      ('hip_abduction_rom'),
      ('hip_internal_rotation_rom'),
      ('ankle_plantarflexion_rom'),
      ('ankle_inversion_rom')
  ) as seed(capability_code)
  left join public.movement_capabilities mc
    on mc.capability_code = seed.capability_code
   and mc.status = 'active'
  where mc.id is null;

  if coalesce(array_length(missing_capabilities, 1), 0) > 0 then
    raise exception 'Missing capabilities for secondary_rom_l3_wave11: %', missing_capabilities;
  end if;

  select array_agg(seed.observation_code order by seed.observation_code)
  into missing_observations
  from (
    values
      ('ROM_shoulder_abduction'),
      ('ROM_shoulder_internal_rotation'),
      ('ROM_hip_abduction'),
      ('ROM_hip_internal_rotation'),
      ('ROM_ankle_plantarflexion'),
      ('ROM_ankle_inversion')
  ) as seed(observation_code)
  left join public.observation_taxonomy ot
    on ot.code = seed.observation_code
   and ot.code_system = 'http://physiokorea.com/fhir/observation'
  where ot.id is null;

  if coalesce(array_length(missing_observations, 1), 0) > 0 then
    raise exception 'Missing observations for secondary_rom_l3_wave11: %', missing_observations;
  end if;
end $$;
with seed as (
  select * from (values
    ('ROM_shoulder_abduction', 'shoulder_abduction_rom', '어깨 외전 ROM', 'deg', '>=', 150::numeric, '>=', 120::numeric, '<', 120::numeric, true, 'Use assisted scaption, table slide, wall slide in lower range, or isometric shoulder work before full-range lateral raise or overhead loading.', 'If pain arc, shoulder hiking, night pain, or symptom increase appears, reduce range/load and reassess scapular control.', 'Shoulder abduction ROM gates overhead and lateral-raise entry but must be interpreted with pain, irritability, scapular control, and diagnosis context.', jsonb_build_array('https://archive.cdc.gov/www_cdc_gov/ncbddd/jointrom/index.html')),
    ('ROM_shoulder_internal_rotation', 'shoulder_internal_rotation_rom', '어깨 내회전 ROM', 'deg', '>=', 60::numeric, '>=', 45::numeric, '<', 45::numeric, true, 'Use sleeper/cross-body stretch within tolerance, towel-assisted internal rotation, or low-load cuff/scapular control before behind-back or overhead internal-rotation tasks.', 'If anterior shoulder pain, posterior shoulder pinch, or next-day irritability increases, reduce range and keep work below symptom threshold.', 'Internal rotation ROM varies by position and sport; use side comparison and symptom response before strong loading decisions.', jsonb_build_array('https://archive.cdc.gov/www_cdc_gov/ncbddd/jointrom/index.html')),
    ('ROM_hip_abduction', 'hip_abduction_rom', '고관절 외전 ROM', 'deg', '>=', 35::numeric, '>=', 25::numeric, '<', 25::numeric, true, 'Use side-lying supported abduction, clamshell, reduced-range lateral step, or mobility-first work before wide-stance squat/lunge or loaded lateral work.', 'If groin pain, pelvic compensation, or lateral hip irritability increases, reduce range/load and reassess control.', 'Hip abduction ROM gates lateral stance and frontal-plane loading but should be paired with hip strength and pain response.', jsonb_build_array('https://archive.cdc.gov/www_cdc_gov/ncbddd/jointrom/index.html')),
    ('ROM_hip_internal_rotation', 'hip_internal_rotation_rom', '고관절 내회전 ROM', 'deg', '>=', 30::numeric, '>=', 20::numeric, '<', 20::numeric, true, 'Use supine/prone gentle hip rotation, short-arc control, or squat/lunge depth reduction before deep squat, pivot, or cutting patterns.', 'If groin pain, pinch, or next-day irritability increases, reduce depth/rotation and monitor symptom response.', 'Hip internal rotation ROM affects squat depth, gait/turning, and sport tasks but is not diagnosis-specific by itself.', jsonb_build_array('https://archive.cdc.gov/www_cdc_gov/ncbddd/jointrom/index.html')),
    ('ROM_ankle_plantarflexion', 'ankle_plantarflexion_rom', '발목 저측굴곡 ROM', 'deg', '>=', 40::numeric, '>=', 30::numeric, '<', 30::numeric, true, 'Use active plantarflexion, seated heel raise, short-range calf work, or mobility-first drills before full heel raise, hopping, or push-off tasks.', 'If calf/Achilles pain, swelling, or altered push-off increases, reduce range/load and monitor 24-hour response.', 'Ankle plantarflexion ROM gates push-off and calf loading, but tissue irritability and strength capacity must guide progression.', jsonb_build_array('https://archive.cdc.gov/www_cdc_gov/ncbddd/jointrom/index.html')),
    ('ROM_ankle_inversion', 'ankle_inversion_rom', '발목 내번 ROM', 'deg', '>=', 30::numeric, '>=', 20::numeric, '<', 20::numeric, true, 'Use pain-free ankle circles, band-free inversion control, supported balance, or short-arc mobility before unstable-surface or lateral ankle loading.', 'If lateral ankle pain, giving-way, swelling, or apprehension increases, reduce range/stability demand and reassess.', 'Ankle inversion ROM should be paired with ligament irritability, proprioception, swelling, and giving-way history.', jsonb_build_array('https://archive.cdc.gov/www_cdc_gov/ncbddd/jointrom/index.html'))
  ) as seed(
    observation_code,
    capability_code,
    capability_label_ko,
    value_unit,
    ready_operator,
    ready_value,
    caution_operator,
    caution_value,
    regress_operator,
    regress_value,
    laterality_required,
    default_regression,
    symptom_response_rule,
    review_note,
    source_refs
  )
),
rule_seed as (
  select
    seed.*,
    jsonb_build_object(
      'basis', 'mvp_screening_default_not_diagnostic',
      'source_tools', jsonb_build_array('secondary_rom_l3_wave11'),
      'decision_bands', jsonb_build_array(
        jsonb_build_object(
          'label', 'ready',
          'plain_ko', '기본 운동 가능',
          'operator', ready_operator,
          'value', ready_value,
          'unit', value_unit
        ),
        jsonb_build_object(
          'label', 'caution',
          'plain_ko', '주의/보조 필요',
          'operator', caution_operator,
          'value', caution_value,
          'unit', value_unit
        ),
        jsonb_build_object(
          'label', 'regress',
          'plain_ko', '쉬운 버전 우선',
          'operator', regress_operator,
          'value', regress_value,
          'unit', value_unit
        )
      ),
      'default_regression', default_regression,
      'laterality_required', laterality_required,
      'symptom_response_rule', symptom_response_rule,
      'review_note', review_note
    ) as l3_rules
  from seed
)
update public.movement_capabilities mc
set
  properties = coalesce(mc.properties, '{}'::jsonb)
    || jsonb_build_object(
      'mvp_completion_level', 'L3',
      'plain_status', '처방 판단 가능',
      'l3_rules', rule_seed.l3_rules,
      'source_refs', rule_seed.source_refs,
      'seed_wave', 'secondary_rom_l3_wave11'
    ),
  updated_at = now()
from rule_seed
where mc.capability_code = rule_seed.capability_code;
with seed as (
  select * from (values
    ('ROM_shoulder_abduction', 'shoulder_abduction_rom', '어깨 외전 ROM', 'deg', '>=', 150::numeric, '>=', 120::numeric, '<', 120::numeric, true, 'Use assisted scaption, table slide, wall slide in lower range, or isometric shoulder work before full-range lateral raise or overhead loading.', 'If pain arc, shoulder hiking, night pain, or symptom increase appears, reduce range/load and reassess scapular control.', 'Shoulder abduction ROM gates overhead and lateral-raise entry but must be interpreted with pain, irritability, scapular control, and diagnosis context.', jsonb_build_array('https://archive.cdc.gov/www_cdc_gov/ncbddd/jointrom/index.html')),
    ('ROM_shoulder_internal_rotation', 'shoulder_internal_rotation_rom', '어깨 내회전 ROM', 'deg', '>=', 60::numeric, '>=', 45::numeric, '<', 45::numeric, true, 'Use sleeper/cross-body stretch within tolerance, towel-assisted internal rotation, or low-load cuff/scapular control before behind-back or overhead internal-rotation tasks.', 'If anterior shoulder pain, posterior shoulder pinch, or next-day irritability increases, reduce range and keep work below symptom threshold.', 'Internal rotation ROM varies by position and sport; use side comparison and symptom response before strong loading decisions.', jsonb_build_array('https://archive.cdc.gov/www_cdc_gov/ncbddd/jointrom/index.html')),
    ('ROM_hip_abduction', 'hip_abduction_rom', '고관절 외전 ROM', 'deg', '>=', 35::numeric, '>=', 25::numeric, '<', 25::numeric, true, 'Use side-lying supported abduction, clamshell, reduced-range lateral step, or mobility-first work before wide-stance squat/lunge or loaded lateral work.', 'If groin pain, pelvic compensation, or lateral hip irritability increases, reduce range/load and reassess control.', 'Hip abduction ROM gates lateral stance and frontal-plane loading but should be paired with hip strength and pain response.', jsonb_build_array('https://archive.cdc.gov/www_cdc_gov/ncbddd/jointrom/index.html')),
    ('ROM_hip_internal_rotation', 'hip_internal_rotation_rom', '고관절 내회전 ROM', 'deg', '>=', 30::numeric, '>=', 20::numeric, '<', 20::numeric, true, 'Use supine/prone gentle hip rotation, short-arc control, or squat/lunge depth reduction before deep squat, pivot, or cutting patterns.', 'If groin pain, pinch, or next-day irritability increases, reduce depth/rotation and monitor symptom response.', 'Hip internal rotation ROM affects squat depth, gait/turning, and sport tasks but is not diagnosis-specific by itself.', jsonb_build_array('https://archive.cdc.gov/www_cdc_gov/ncbddd/jointrom/index.html')),
    ('ROM_ankle_plantarflexion', 'ankle_plantarflexion_rom', '발목 저측굴곡 ROM', 'deg', '>=', 40::numeric, '>=', 30::numeric, '<', 30::numeric, true, 'Use active plantarflexion, seated heel raise, short-range calf work, or mobility-first drills before full heel raise, hopping, or push-off tasks.', 'If calf/Achilles pain, swelling, or altered push-off increases, reduce range/load and monitor 24-hour response.', 'Ankle plantarflexion ROM gates push-off and calf loading, but tissue irritability and strength capacity must guide progression.', jsonb_build_array('https://archive.cdc.gov/www_cdc_gov/ncbddd/jointrom/index.html')),
    ('ROM_ankle_inversion', 'ankle_inversion_rom', '발목 내번 ROM', 'deg', '>=', 30::numeric, '>=', 20::numeric, '<', 20::numeric, true, 'Use pain-free ankle circles, band-free inversion control, supported balance, or short-arc mobility before unstable-surface or lateral ankle loading.', 'If lateral ankle pain, giving-way, swelling, or apprehension increases, reduce range/stability demand and reassess.', 'Ankle inversion ROM should be paired with ligament irritability, proprioception, swelling, and giving-way history.', jsonb_build_array('https://archive.cdc.gov/www_cdc_gov/ncbddd/jointrom/index.html'))
  ) as seed(
    observation_code,
    capability_code,
    capability_label_ko,
    value_unit,
    ready_operator,
    ready_value,
    caution_operator,
    caution_value,
    regress_operator,
    regress_value,
    laterality_required,
    default_regression,
    symptom_response_rule,
    review_note,
    source_refs
  )
)
update public.observation_taxonomy ot
set
  default_value_type = 'quantity',
  default_unit = seed.value_unit,
  interpretation_guide = coalesce(ot.interpretation_guide, '{}'::jsonb)
    || jsonb_build_object(
      'seed_wave', 'secondary_rom_l3_wave11',
      'plain_status', '처방 판단 가능',
      'capability_code', seed.capability_code,
      'capability_label_ko', seed.capability_label_ko,
      'direction', 'higher_is_better',
      'laterality_required', seed.laterality_required,
      'decision_bands', jsonb_build_array(
        'ready: ' || seed.ready_operator || seed.ready_value || seed.value_unit,
        'caution: ' || seed.caution_operator || seed.caution_value || seed.value_unit,
        'regress: ' || seed.regress_operator || seed.regress_value || seed.value_unit
      ),
      'safety_note', seed.review_note
    ),
  updated_at = now()
from seed
where ot.code = seed.observation_code
  and ot.code_system = 'http://physiokorea.com/fhir/observation';
with seed as (
  select * from (values
    ('ROM_shoulder_abduction', 'shoulder_abduction_rom', '어깨 외전 ROM', 'deg', '>=', 150::numeric, '>=', 120::numeric, '<', 120::numeric, true, 'Use assisted scaption, table slide, wall slide in lower range, or isometric shoulder work before full-range lateral raise or overhead loading.', 'If pain arc, shoulder hiking, night pain, or symptom increase appears, reduce range/load and reassess scapular control.', 'Shoulder abduction ROM gates overhead and lateral-raise entry but must be interpreted with pain, irritability, scapular control, and diagnosis context.', jsonb_build_array('https://archive.cdc.gov/www_cdc_gov/ncbddd/jointrom/index.html')),
    ('ROM_shoulder_internal_rotation', 'shoulder_internal_rotation_rom', '어깨 내회전 ROM', 'deg', '>=', 60::numeric, '>=', 45::numeric, '<', 45::numeric, true, 'Use sleeper/cross-body stretch within tolerance, towel-assisted internal rotation, or low-load cuff/scapular control before behind-back or overhead internal-rotation tasks.', 'If anterior shoulder pain, posterior shoulder pinch, or next-day irritability increases, reduce range and keep work below symptom threshold.', 'Internal rotation ROM varies by position and sport; use side comparison and symptom response before strong loading decisions.', jsonb_build_array('https://archive.cdc.gov/www_cdc_gov/ncbddd/jointrom/index.html')),
    ('ROM_hip_abduction', 'hip_abduction_rom', '고관절 외전 ROM', 'deg', '>=', 35::numeric, '>=', 25::numeric, '<', 25::numeric, true, 'Use side-lying supported abduction, clamshell, reduced-range lateral step, or mobility-first work before wide-stance squat/lunge or loaded lateral work.', 'If groin pain, pelvic compensation, or lateral hip irritability increases, reduce range/load and reassess control.', 'Hip abduction ROM gates lateral stance and frontal-plane loading but should be paired with hip strength and pain response.', jsonb_build_array('https://archive.cdc.gov/www_cdc_gov/ncbddd/jointrom/index.html')),
    ('ROM_hip_internal_rotation', 'hip_internal_rotation_rom', '고관절 내회전 ROM', 'deg', '>=', 30::numeric, '>=', 20::numeric, '<', 20::numeric, true, 'Use supine/prone gentle hip rotation, short-arc control, or squat/lunge depth reduction before deep squat, pivot, or cutting patterns.', 'If groin pain, pinch, or next-day irritability increases, reduce depth/rotation and monitor symptom response.', 'Hip internal rotation ROM affects squat depth, gait/turning, and sport tasks but is not diagnosis-specific by itself.', jsonb_build_array('https://archive.cdc.gov/www_cdc_gov/ncbddd/jointrom/index.html')),
    ('ROM_ankle_plantarflexion', 'ankle_plantarflexion_rom', '발목 저측굴곡 ROM', 'deg', '>=', 40::numeric, '>=', 30::numeric, '<', 30::numeric, true, 'Use active plantarflexion, seated heel raise, short-range calf work, or mobility-first drills before full heel raise, hopping, or push-off tasks.', 'If calf/Achilles pain, swelling, or altered push-off increases, reduce range/load and monitor 24-hour response.', 'Ankle plantarflexion ROM gates push-off and calf loading, but tissue irritability and strength capacity must guide progression.', jsonb_build_array('https://archive.cdc.gov/www_cdc_gov/ncbddd/jointrom/index.html')),
    ('ROM_ankle_inversion', 'ankle_inversion_rom', '발목 내번 ROM', 'deg', '>=', 30::numeric, '>=', 20::numeric, '<', 20::numeric, true, 'Use pain-free ankle circles, band-free inversion control, supported balance, or short-arc mobility before unstable-surface or lateral ankle loading.', 'If lateral ankle pain, giving-way, swelling, or apprehension increases, reduce range/stability demand and reassess.', 'Ankle inversion ROM should be paired with ligament irritability, proprioception, swelling, and giving-way history.', jsonb_build_array('https://archive.cdc.gov/www_cdc_gov/ncbddd/jointrom/index.html'))
  ) as seed(
    observation_code,
    capability_code,
    capability_label_ko,
    value_unit,
    ready_operator,
    ready_value,
    caution_operator,
    caution_value,
    regress_operator,
    regress_value,
    laterality_required,
    default_regression,
    symptom_response_rule,
    review_note,
    source_refs
  )
)
update public.movement_capability_observation_mappings map
set
  default_unit = seed.value_unit,
  value_type_hint = 'quantity',
  metadata = coalesce(map.metadata, '{}'::jsonb)
    || jsonb_build_object(
      'seed_wave', 'secondary_rom_l3_wave11',
      'completion_level', 'L3',
      'plain_status', '처방 판단 가능',
      'capability_code', seed.capability_code,
      'normalization', jsonb_build_object(
        'canonical_unit', seed.value_unit,
        'laterality_required', seed.laterality_required
      )
    ),
  updated_at = now()
from seed
where map.observation_code = seed.observation_code
  and map.status = 'active';
with seed as (
  select * from (values
    ('ROM_shoulder_abduction', 'shoulder_abduction_rom', '어깨 외전 ROM', 'deg', '>=', 150::numeric, '>=', 120::numeric, '<', 120::numeric, true, 'Use assisted scaption, table slide, wall slide in lower range, or isometric shoulder work before full-range lateral raise or overhead loading.', 'If pain arc, shoulder hiking, night pain, or symptom increase appears, reduce range/load and reassess scapular control.', 'Shoulder abduction ROM gates overhead and lateral-raise entry but must be interpreted with pain, irritability, scapular control, and diagnosis context.', jsonb_build_array('https://archive.cdc.gov/www_cdc_gov/ncbddd/jointrom/index.html')),
    ('ROM_shoulder_internal_rotation', 'shoulder_internal_rotation_rom', '어깨 내회전 ROM', 'deg', '>=', 60::numeric, '>=', 45::numeric, '<', 45::numeric, true, 'Use sleeper/cross-body stretch within tolerance, towel-assisted internal rotation, or low-load cuff/scapular control before behind-back or overhead internal-rotation tasks.', 'If anterior shoulder pain, posterior shoulder pinch, or next-day irritability increases, reduce range and keep work below symptom threshold.', 'Internal rotation ROM varies by position and sport; use side comparison and symptom response before strong loading decisions.', jsonb_build_array('https://archive.cdc.gov/www_cdc_gov/ncbddd/jointrom/index.html')),
    ('ROM_hip_abduction', 'hip_abduction_rom', '고관절 외전 ROM', 'deg', '>=', 35::numeric, '>=', 25::numeric, '<', 25::numeric, true, 'Use side-lying supported abduction, clamshell, reduced-range lateral step, or mobility-first work before wide-stance squat/lunge or loaded lateral work.', 'If groin pain, pelvic compensation, or lateral hip irritability increases, reduce range/load and reassess control.', 'Hip abduction ROM gates lateral stance and frontal-plane loading but should be paired with hip strength and pain response.', jsonb_build_array('https://archive.cdc.gov/www_cdc_gov/ncbddd/jointrom/index.html')),
    ('ROM_hip_internal_rotation', 'hip_internal_rotation_rom', '고관절 내회전 ROM', 'deg', '>=', 30::numeric, '>=', 20::numeric, '<', 20::numeric, true, 'Use supine/prone gentle hip rotation, short-arc control, or squat/lunge depth reduction before deep squat, pivot, or cutting patterns.', 'If groin pain, pinch, or next-day irritability increases, reduce depth/rotation and monitor symptom response.', 'Hip internal rotation ROM affects squat depth, gait/turning, and sport tasks but is not diagnosis-specific by itself.', jsonb_build_array('https://archive.cdc.gov/www_cdc_gov/ncbddd/jointrom/index.html')),
    ('ROM_ankle_plantarflexion', 'ankle_plantarflexion_rom', '발목 저측굴곡 ROM', 'deg', '>=', 40::numeric, '>=', 30::numeric, '<', 30::numeric, true, 'Use active plantarflexion, seated heel raise, short-range calf work, or mobility-first drills before full heel raise, hopping, or push-off tasks.', 'If calf/Achilles pain, swelling, or altered push-off increases, reduce range/load and monitor 24-hour response.', 'Ankle plantarflexion ROM gates push-off and calf loading, but tissue irritability and strength capacity must guide progression.', jsonb_build_array('https://archive.cdc.gov/www_cdc_gov/ncbddd/jointrom/index.html')),
    ('ROM_ankle_inversion', 'ankle_inversion_rom', '발목 내번 ROM', 'deg', '>=', 30::numeric, '>=', 20::numeric, '<', 20::numeric, true, 'Use pain-free ankle circles, band-free inversion control, supported balance, or short-arc mobility before unstable-surface or lateral ankle loading.', 'If lateral ankle pain, giving-way, swelling, or apprehension increases, reduce range/stability demand and reassess.', 'Ankle inversion ROM should be paired with ligament irritability, proprioception, swelling, and giving-way history.', jsonb_build_array('https://archive.cdc.gov/www_cdc_gov/ncbddd/jointrom/index.html'))
  ) as seed(
    observation_code,
    capability_code,
    capability_label_ko,
    value_unit,
    ready_operator,
    ready_value,
    caution_operator,
    caution_value,
    regress_operator,
    regress_value,
    laterality_required,
    default_regression,
    symptom_response_rule,
    review_note,
    source_refs
  )
)
update public.exercise_requirements er
set
  value_unit = coalesce(er.value_unit, seed.value_unit),
  metadata = coalesce(er.metadata, '{}'::jsonb)
    || jsonb_build_object(
      'seed_wave', 'secondary_rom_l3_wave11',
      'requirement_rule_family', 'secondary_rom_l3_wave11',
      'l3_rule_capability_code', seed.capability_code
    ),
  updated_at = now()
from seed
join public.movement_capabilities mc
  on mc.capability_code = seed.capability_code
where er.capability_id = mc.id
  and er.status = 'active';
