ALTER TABLE assessment_form_templates
  ADD COLUMN IF NOT EXISTS mdc_value              numeric,
  ADD COLUMN IF NOT EXISTS higher_is_better        boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS score_min               numeric,
  ADD COLUMN IF NOT EXISTS score_max               numeric,
  ADD COLUMN IF NOT EXISTS action_on_mcid_achieved text,
  ADD COLUMN IF NOT EXISTS action_on_worsened      text,
  ADD COLUMN IF NOT EXISTS action_on_no_change     text,
  ADD COLUMN IF NOT EXISTS evidence_level          varchar,
  ADD COLUMN IF NOT EXISTS evidence_source         varchar,
  ADD COLUMN IF NOT EXISTS evidence_year           int4,
  ADD COLUMN IF NOT EXISTS condition_overrides     jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS mdc_90                  numeric,
  ADD COLUMN IF NOT EXISTS mdc_95                  numeric,
  ADD COLUMN IF NOT EXISTS icc                     numeric,
  ADD COLUMN IF NOT EXISTS sem                     numeric,
  ADD COLUMN IF NOT EXISTS mcid_range              varchar,
  ADD COLUMN IF NOT EXISTS body_region             varchar,
  ADD COLUMN IF NOT EXISTS is_active               boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS updated_at              timestamptz DEFAULT now();;
